# Generated by Django 4.2 on 2024-11-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradelevels',
            fields=[
                ('grade_level', models.CharField(db_column='grade_Level', max_length=90, primary_key=True, serialize=False)),
                ('school_year', models.CharField(db_column='school_Year', max_length=90)),
                ('semester', models.CharField(db_column='Semester', max_length=90)),
            ],
            options={
                'db_table': 'gradelevels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('gid', models.AutoField(db_column='GID', primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('last_name', models.CharField(db_column='last_Name', max_length=90)),
                ('first_name', models.CharField(db_column='first_Name', max_length=90)),
                ('middle_name', models.CharField(db_column='middle_Name', max_length=90)),
                ('relationship', models.CharField(max_length=90)),
                ('occupation', models.CharField(max_length=90)),
                ('noe', models.CharField(db_column='NOE', max_length=90)),
                ('business', models.CharField(max_length=90)),
                ('email_address', models.CharField(db_column='email_Address', max_length=90)),
                ('contact_no', models.CharField(db_column='contact_No', max_length=90)),
                ('address', models.CharField(db_column='Address', max_length=90)),
            ],
            options={
                'db_table': 'guardian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('mon_id', models.AutoField(db_column='mon_ID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=90)),
                ('academic_year', models.CharField(db_column='academic_Year', max_length=90)),
            ],
            options={
                'db_table': 'monitoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('pid', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='last_Name', max_length=90)),
                ('first_name', models.CharField(db_column='first_Name', max_length=90)),
                ('middle_name', models.CharField(db_column='middle_Name', max_length=90)),
                ('occupation', models.CharField(max_length=90)),
                ('noe', models.CharField(db_column='NOE', max_length=90)),
                ('business', models.CharField(max_length=90)),
                ('email_address', models.CharField(db_column='email_Address', max_length=90)),
                ('contact_no', models.CharField(db_column='contact_No', max_length=11)),
                ('address', models.CharField(db_column='Address', max_length=90)),
            ],
            options={
                'db_table': 'parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentstudent',
            fields=[
                ('gid', models.IntegerField(db_column='GID', primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('relationship', models.CharField(max_length=90)),
                ('isguardian', models.IntegerField(db_column='isGuardian')),
            ],
            options={
                'db_table': 'parentstudent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preliminarycharges',
            fields=[
                ('pc_id', models.AutoField(db_column='PC_ID', primary_key=True, serialize=False)),
                ('grade_level', models.CharField(db_column='grade_Level', max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('academic_year', models.CharField(db_column='academic_Year', max_length=90)),
                ('date_added', models.DateField(db_column='date_Added')),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'preliminarycharges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Previousschooling',
            fields=[
                ('ps_id', models.AutoField(db_column='ps_ID', primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('grade_level', models.CharField(db_column='grade_Level', max_length=90)),
                ('nosa', models.CharField(db_column='NOSA', max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('year_attended', models.CharField(db_column='year_Attended', max_length=90)),
                ('reasonfortransfer', models.CharField(db_column='ReasonForTransfer', max_length=90)),
            ],
            options={
                'db_table': 'previousschooling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('req_id', models.IntegerField(db_column='req_ID', primary_key=True, serialize=False)),
                ('r_name', models.CharField(db_column='r_Name', max_length=90)),
                ('isactive', models.IntegerField(db_column='isActive')),
            ],
            options={
                'db_table': 'requirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requirementsbridge',
            fields=[
                ('req_id', models.IntegerField(db_column='req_ID', primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('datepass', models.DateField(db_column='datePass')),
                ('note', models.CharField(max_length=90)),
                ('ispass', models.IntegerField(db_column='isPass')),
            ],
            options={
                'db_table': 'requirementsbridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scharges',
            fields=[
                ('table_pk', models.AutoField(db_column='table_PK', primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=90)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('atm_balance', models.IntegerField(db_column='ATM_Balance')),
            ],
            options={
                'db_table': 'scharges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cl', models.CharField(max_length=10)),
                ('present_status', models.CharField(max_length=10)),
                ('roll', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'school_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolexpenses',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('description', models.CharField(db_column='Description', max_length=90)),
                ('amount', models.FloatField(db_column='Amount')),
                ('sy', models.CharField(blank=True, db_column='SY', max_length=90, null=True)),
            ],
            options={
                'db_table': 'schoolexpenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolincome',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('description', models.CharField(db_column='Description', max_length=90)),
                ('amount', models.FloatField(db_column='Amount')),
                ('sy', models.CharField(blank=True, db_column='SY', max_length=90, null=True)),
            ],
            options={
                'db_table': 'schoolincome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=500)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'school_notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolStudentextra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('cl', models.CharField(max_length=10)),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'school_studentextra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolTeacherextra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('joindate', models.DateField()),
                ('mobile', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'school_teacherextra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spayment',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('table_pk', models.CharField(db_column='table_PK', max_length=90)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=90)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('atm_balance', models.IntegerField(db_column='ATM_Balance')),
            ],
            options={
                'db_table': 'spayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardfinancialdescription',
            fields=[
                ('financial_description', models.CharField(db_column='financial_Description', max_length=90, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'standardfinancialdescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardgradelevel',
            fields=[
                ('grade_level_name', models.CharField(db_column='grade_Level_Name', max_length=90, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'standardgradelevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardschoolyear',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('school_year_name', models.CharField(db_column='school_Year_Name', max_length=90)),
                ('isactive', models.IntegerField(db_column='isActive')),
                ('starting_date', models.DateField(db_column='Starting_Date')),
                ('ending_date', models.DateField(db_column='Ending_Date')),
            ],
            options={
                'db_table': 'standardschoolyear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardsubjecttime',
            fields=[
                ('subject_time_name', models.CharField(db_column='subject_Time_Name', max_length=90, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'standardsubjecttime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('studentid', models.CharField(db_column='StudentID', max_length=90)),
                ('lrn_no', models.CharField(db_column='LRN_No', max_length=90)),
                ('last_name', models.CharField(db_column='last_Name', max_length=90)),
                ('first_name', models.CharField(db_column='first_Name', max_length=90)),
                ('middle_name', models.CharField(db_column='middle_Name', max_length=90)),
                ('nick_name', models.CharField(db_column='nick_Name', max_length=90)),
                ('sex', models.CharField(max_length=90)),
                ('dob', models.DateField(db_column='DOB')),
                ('age', models.CharField(max_length=90)),
                ('bo', models.CharField(db_column='BO', max_length=1000)),
                ('home_address', models.CharField(db_column='home_Address', max_length=90)),
                ('religion', models.CharField(max_length=90)),
                ('tvprogramsmoviesbooks', models.CharField(db_column='TVProgramsMoviesBooks', max_length=90)),
                ('first_language', models.CharField(db_column='first_Language', max_length=90)),
                ('language_spoken', models.CharField(db_column='language_Spoken', max_length=90)),
                ('pob', models.CharField(db_column='POB', max_length=90)),
                ('interest', models.CharField(db_column='Interest', max_length=90)),
                ('if_voucher', models.IntegerField(db_column='If_Voucher')),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentenrollsubject',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studentenrollsubject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentregister',
            fields=[
                ('sr_id', models.CharField(db_column='SR_ID', max_length=90, primary_key=True, serialize=False)),
                ('stud_id', models.CharField(db_column='Stud_ID', max_length=90)),
                ('academic_year', models.CharField(db_column='academic_Year', max_length=90)),
                ('grade_level', models.CharField(db_column='grade_Level', max_length=90)),
                ('dor', models.DateField(db_column='DOR')),
                ('nos', models.CharField(db_column='NOS', max_length=90)),
                ('nosar', models.CharField(db_column='NOSAR', max_length=90)),
                ('strand', models.CharField(db_column='Strand', max_length=90)),
                ('status', models.CharField(db_column='Status', max_length=90)),
                ('date_entered', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studentregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ref', models.AutoField(db_column='Ref', primary_key=True, serialize=False)),
                ('subject_code', models.CharField(db_column='subject_Code', max_length=90)),
                ('sub_name', models.CharField(db_column='sub_Name', max_length=90)),
                ('sub_time', models.CharField(db_column='sub_Time', max_length=90)),
                ('sub_room', models.CharField(db_column='sub_Room', max_length=90)),
                ('teacher_id', models.CharField(db_column='teacher_ID', max_length=90)),
                ('grade_level', models.CharField(db_column='grade_Level', max_length=90)),
                ('academic_year', models.CharField(db_column='academic_Year', max_length=90)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systemaccount',
            fields=[
                ('sa_no', models.AutoField(db_column='SA_No', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ID', max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('email_address', models.CharField(db_column='email_Address', max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('username', models.CharField(max_length=90)),
                ('contact_no', models.CharField(db_column='contact_No', max_length=90)),
                ('position', models.CharField(max_length=90)),
                ('picture', models.TextField(db_column='Picture')),
            ],
            options={
                'db_table': 'systemaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tcharges',
            fields=[
                ('tc_id', models.AutoField(db_column='tc_ID', primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(db_column='teacher_ID', max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('atm_balance', models.CharField(db_column='ATM_Balance', max_length=90)),
            ],
            options={
                'db_table': 'tcharges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(db_column='teacher_ID', max_length=90, primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='last_Name', max_length=90)),
                ('first_name', models.CharField(db_column='first_Name', max_length=90)),
                ('middle_name', models.CharField(db_column='middle_Name', max_length=90)),
                ('sex', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('dob', models.DateField(db_column='DOB')),
                ('age', models.IntegerField()),
                ('home_address', models.CharField(db_column='home_Address', max_length=90)),
                ('contact_no', models.IntegerField(db_column='contact_No')),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('stud', models.OneToOneField(db_column='Stud_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school.student')),
                ('stud_grade', models.CharField(db_column='stud_Grade', max_length=90)),
                ('academic_year', models.CharField(db_column='academic_Year', max_length=90)),
                ('grading_period', models.CharField(db_column='grading_Period', max_length=90)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
    ]
